<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="3"
           failures="1"
           errors="0"
           skipped="1"
           time="0.032">
  <properties />
            <testcase name="verifyTitleOne" time="0.016" classname="TestClassOne">
                <failure type="java.lang.AssertionError"
                  message="expected [Registe] but found [Register]"
              >
<![CDATA[java.lang.AssertionError: expected [Registe] but found [Register]
  org.testng.Assert.fail(Assert.java:93)
  org.testng.Assert.failNotEquals(Assert.java:512)
  org.testng.Assert.assertEqualsImpl(Assert.java:134)
  org.testng.Assert.assertEquals(Assert.java:115)
  org.testng.Assert.assertEquals(Assert.java:189)
  org.testng.Assert.assertEquals(Assert.java:199)
  TestClassOne.verifyTitleOne(TestClassOne.java:22)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:776)
  org.testng.TestRunner.run(TestRunner.java:634)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
  org.testng.SuiteRunner.run(SuiteRunner.java:334)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
  org.testng.TestNG.runSuites(TestNG.java:1161)
  org.testng.TestNG.run(TestNG.java:1129)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
            <testcase name="verifyTextOne" time="0.0" classname="TestClassOne">
          <skipped />
    </testcase>
  
            <testcase name="verifyUrlOne" time="0.016" classname="TestClassOne" />
      
</testsuite>
